PuT http://localhost:5000/users/643c3ec66d951c07b8491fbb
Content-Type: application/json

{
    "name": "kassim ali",
    "email": "omari@special.com",
    "username": "omiero",
    "password": "kassimali2001"
}